# Generated by Django 5.0.6 on 2024-05-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profilePicture",
            field=models.URLField(
                default="https://portfolioapi-422802.uc.r.appspot.com/static/images/default/blank-profile-picture.png"
            ),
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="UserProfiles",
        ),
    ]
