name: Deploy to GAE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup python 3.11.5
        uses: actions/setup-python@v2
        with:
          python-version: "3.11.5"

      - name: Install Requirements
        run: |
          pip install -r requirements.txt

      - name: GCloud Authenticate
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use GCloud CLI
        run: |
          gcloud info

      - name: Gather Static Files
        run: |
          python manage.py collectstatic --noinput

      - name: Run Migrations
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          version: v1
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
